# The Docker image that will be used to build your app
image: oven/bun:1
# Functions that should be executed before the build script is run
cache:
  paths:
    - node_modules/

before_script:
  - bun install --frozen-lockfile
pages:
  script:
    - bun run build
    - mkdir -p public
    - cp -r dist/. public/
    - rm -rf dist
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
